### ISSUE TITLE
Font family not found in RHEL7 with error SixLabors.Fonts.FontFamilyNotFoundException

### ISSUE THREAD

**Issue by khushwaqt** [aliasadidev/SixLaborsCaptcha#6]
I am trying to run my app on Kubernetes  RHEL server. But every time i am getting **SixLabors.Fonts.FontFamilyNotFoundException**. 
I have double checked and verified that the font is available inside /usr/share/fonts/. I have also tried adding a custom font as described in readme file but still no luck. Here is stackstace for same. 

this is my code 

```
 public async Task<string> GetCaptchaImage(string test)
        {
            _log.LogInformation(string.Format("GetCaptchaImage- Font name is {0}", Environment.GetEnvironmentVariable("font_name")));
            _log.LogInformation(string.Format("GetCaptchaImage- A bitmap of 130x80"));
            var slc = new SixLaborsCaptchaModule(new SixLaborsCaptchaOptions
            {
                DrawLines = 7,
                TextColor = new Color[] { Color.Blue, Color.Black },
                Width = 130,
                Height = 80,
                FontFamilies = new string[] { Environment.GetEnvironmentVariable("font_name") },
            });
            _log.LogInformation(string.Format("GetCaptchaImage- Generating random text"));
            var captchaText = Extentions.GetUniqueKey(6).ToUpper();
            _log.LogInformation(string.Format("GetCaptchaImage- Generating bitmap..."));
            var images = slc.Generate(captchaText);  // this is line 945
            _log.LogInformation(string.Format("GetCaptchaImage- Returning base64 image..."));
            return Convert.ToBase64String(images);
        }
```

```
DejaVuSans could not be found.  
SixLabors.Fonts.FontFamilyNotFoundException
"   at SixLabors.Fonts.FontCollection.GetImpl(String name CultureInfo culture)
   at SixLabors.Fonts.FontCollection.Get(String name)
   at SixLabors.Fonts.SystemFontCollection.Get(String name)
   at SixLabors.Fonts.SystemFonts.CreateFont(String name Single size FontStyle style)
   at SixLaborsCaptcha.Core.SixLaborsCaptchaModule.Generate(String stringText)
   at classname.GetCaptchaImage(String msisdn) 
   in Classname.cs:line 945
   at Clanname.GetCaptcha(String msisdn) in 
   classname.cs:line 609"
```
![image](https://user-images.githubusercontent.com/15142925/166158675-2644ddd9-1cd6-463d-b644-30ba3417a7ac.png)

**Comment by khushwaqt** [comment]
My bad, 
Font must be copied to the pod as well.

**Comment by SmRiley** [comment]
In SixLabors,that have SystemFontsCollections,you can use it :
` var fontName = SystemFonts.Collection.Families.FirstOrDefault().Name;`

**Comment by SmRiley** [comment]
@aliasadidev 

> In SixLabors,that have SystemFontsCollections,you can use it : ` var fontName = SystemFonts.Collection.Families.FirstOrDefault().Name;`
@aliasadidev Maybe can use this consider as default font on linux, after all many people want to use it out of the box
